name: SimpleRepair
api: 4.0.0
main: Krishvy\SimpleRepair\SimpleRepair
version: 1.0.0
author: Krishvy

permissions:
  repairhand.use:
    default: op
  repairall.use:
    default: op
  repairarmor.use:
    default: op